#!/usr/bin/env bash
# Displays 'Best School' 10 times
# For 9th iteration, displays 'Best School' then 'Hi' on a new line

kount=0

while [ $kount -lt 10 ]
do
    if [ $kount -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( kount++ ))
done
