#!/usr/bin/env bash
# Script that displays numbers from 1 to 10 
# with varying messages at 4 and 8

kount=0

while [ $kount -lt 10 ]
do
	if  [ "$kount" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$kount" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( kount++ ))
done 
