#!/usr/bin/env bash
# Bash script that distplays numbers from 1 to 20 and:
# display 4 bad luck from China for 4th iteration
# 9  bad luck from Japan for 9th iteration
# 17 bad luck from Italy

kount=1
while [ $kount -le 20 ]
do
    echo "$kount"
    case $kount in
      "4")
        echo "bad luck from China"
        ;;
        "9")
        echo "bad luck from Japan"
        ;;
        "17")
        echo "bad luck from Italy"
        ;;
    esac
    (( kount++ ))
done